apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: {{ .Values.postgres.app }}
spec:
  accessModes:
    - {{ .Values.postgres.storageAccessMode }}
  resources:
    requests:
      storage: {{ .Values.postgres.storageSize }}
  {{- if .Values.postgres.storageClass }}
  storageClassName: {{ .Values.postgres.storageClass | quote }}
  {{- end }}
