# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/postgres

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set Matrix
        id: set-matrix
        run: |
          MATRIX_JSON=$(jq -c . versions.json)
          echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT

  build:
    needs: matrix
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Image Tags
        id: tags
        run: |
          MAJOR="${{ matrix.major }}"
          IS_LATEST="${{ matrix.is_latest }}"
          REPO="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"

          if [ -z "$MAJOR" ]; then
            echo "$matrix"
            echo "ERROR: matrix.major evaluated to empty!"
            exit 1
          fi

          TAG_LIST="${REPO}:${MAJOR}"

          if [ "$IS_LATEST" = "true" ]; then
            TAG_LIST="${TAG_LIST},${REPO}:latest"
          fi

          echo "tags=${TAG_LIST}" >> $GITHUB_OUTPUT

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            VERSION=${{ matrix.version.upstream }}
          platforms: linux/amd64, linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.tags.outputs.tags }}
